name: GS541
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
  - default
dependencies:
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1b
  - paml=4.9
  - pip=19.1
  - python=3.7.3
  - raxml=8.2.12
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - tk=8.6.9
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - attrs==19.1.0
    - backcall==0.1.0
    - biopython==1.73
    - bleach==3.1.0
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - descartes==1.1.0
    - entrypoints==0.3
    - ipykernel==5.1.1
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - mizani==0.5.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - notebook==5.7.8
    - numpy==1.16.4
    - palettable==3.1.1
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.4.0
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - plotnine==0.5.1
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyrsistent==0.15.2
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyzmq==18.0.1
    - qtconsole==4.5.1
    - scipy==1.3.0
    - send2trash==1.5.0
    - six==1.12.0
    - statsmodels==0.9.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.2
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
